resourceClasses:
  - uk.gov.pay.publicauth.resources.PublicAuthResource
  - uk.gov.pay.publicauth.resources.HealthCheckResource
readAllResources: true
sortOutput: true
prettyPrint: true

openAPI:
  info:
    description: 'Publicauth API'
    title: 'Publicauth API'
    version: 'v1.0.0'
  components:
    securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
        description: "The Authorisation token needs to be specified in the 'Authorization' header as `Authorization: Bearer YOUR_API_KEY_HERE`"
